apiVersion: v2
name: network
description: A Helm chart for a blockchain network on Kubernetes
type: application
version: 1.0.3
appVersion: 1.0.3
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
dependencies:
  - name: network-bootstrapper
    version: ">=0.0.0-0"
  - name: network-nodes
    version: ">=0.0.0-0"

