apiVersion: v2
name: network
description: A Helm chart for a blockchain network on Kubernetes
type: application
version: 1.0.1
appVersion: 1.0.1
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
dependencies:
  - name: network-bootstrapper
    version: 1.0.1
  - name: network-nodes
    version: 1.0.1

