apiVersion: v2
name: network-nodes
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "0.1.1"
maintainers:
  - name: SettleMint
    email: support@settlemint.com
    url: https://settlemint.com
